FROM httpd:2.4-alpine

# Enable mod_rewrite
RUN sed -i '/LoadModule rewrite_module/s/^#//g' /usr/local/apache2/conf/httpd.conf && \
    sed -i 's#AllowOverride None#AllowOverride All#' /usr/local/apache2/conf/httpd.conf

# Copy application files
COPY /frontend/index.html /usr/local/apache2/htdocs/index.html
COPY /frontend/app /usr/local/apache2/htdocs/app
COPY /frontend/assets /usr/local/apache2/htdocs/assets
COPY /frontend/.htaccess /usr/local/apache2/htdocs/.htaccess