services:
  frontend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    working_dir: /app/apps/frontend
    command: npx http-server . -p 4200
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: backend
    ports:
      - "3000:3000"
    working_dir: /app/apps/backend
    command: node index.js
