services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - users
      - products
      - orders
  users:
    build: ./services/users
    ports:
      - "3001:3001"
  products:
    build: ./services/products
    ports:
      - "3002:3002"
  orders:
    build: ./services/orders
    ports:
      - "3003:3003"
