services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
  frontend:
    build: ./apps/frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
